default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: dinner_development

test:
  <<: *default
  database: dinner_test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
  user: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
